<? 
#    Installfest Webpage - a php3/postgresql/apache instant Linux
#                          installfest web page and database.
#    Copyright (C) 2000 michaeld@senet.com.au
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
?>

<?
  function navFront() {
?>
      <a href="#Welcome">Welcome</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#Where">When,&nbsp;Where&nbsp;And&nbsp;What?</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#Requirements">Requirements</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#Cost">Cost</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#Sponsors">Sponsors</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#Tshirt">T-Shirts</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#Support">Support</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#Who">Who&nbsp;We&nbsp;Are</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#Contact">Contact</a>
<?
  }
?>

<?
  function navSite() {
?>
      <a href="index.php3">
      Installfest</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="register.php3">
      Register</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="record.php3">
      Installfest&nbsp;Record</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="publicity.php3">
      Publicity</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="admin.php3">
      Installfest&nbsp;Administration</a>
<?
  }
?>

<?
  function navRelated() {
?>
      <a href="http://www.rebel.net.au/~tuxshirt">T-Shirt&nbsp;Competition</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="http://www.rebel.net.au/~lloy0076/linux/ifest/index.html">
      Hints,&nbsp;Tips&nbsp;&&nbsp;Cheatsheet&nbsp;Submission&nbsp;Page</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="http://www.rebel.net.au/~festinisers/index.html">
      Installfest&nbsp;Organiser's&nbsp;Page</a>
<?
  }
?>


<?
  function navRegister() {
?>
      <a href="#Installee">I&nbsp;Want&nbsp;Linux&nbsp;Installed&nbsp;Or&nbsp;Configured.</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#Installer">Help&nbsp;Others&nbsp;Installing&nbsp;or&nbsp;Configuring&nbsp;Linux.</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#BuyTShirt">I&nbsp;Want&nbsp;To&nbsp;Buy&nbsp;A&nbsp;T-Shirt.</a>
<?
  }
?>

<?
  function navPublicity() {
?>
      <a href="#Advert">ASCII Advertisement</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#Logo">Click-thru-Logo</a>
      &nbsp; <b>|</b> &nbsp;
      <a href="#PressRelease">Press&nbsp;Release</a>
<?
  }
?>

